### ISSUE TITLE
Migrate Introduction

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Nitrate_SOP#3]

**Comment by soerenthomsen** [comment]
@gkrahmann could you review that all content has moved correctly?

**Comment by gkrahmann** [comment]
Went through all of it and it looks ok. For a few typos, I created a pull request. Also for the one photo.
I will have a go at the citations.

**Comment by soerenthomsen** [comment]
Thanks a lot for double checking and for going ahead with the citations!
